- name: Install and set Erlang and RabbitMQ repo for {{ansible_os_family}} OS family
  shell: |
    curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash
    curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install versionlock
  yum:
    name: yum-plugin-versionlock

- name:  Install Erlang and RabbitMQ 
  yum:
    name: "{{item}}"
  with_items:
    - "erlang{{rabbitmq_erlang_major_version}}.*"
    - "rabbitmq-server-{{rabbitmq_version}}.*"

- name: Lock Erlang and rabbitmq version
  shell: | 
    yum versionlock erlang
    yum versionlock rabbitmq-server

